/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sunit_gpio_drivers_wiringpi_Native */

#ifndef _Included_sunit_gpio_drivers_wiringpi_Native
#define _Included_sunit_gpio_drivers_wiringpi_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    init
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sunit_gpio_drivers_wiringpi_Native_init
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    pinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sunit_gpio_drivers_wiringpi_Native_pinMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    digitalWrite
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_sunit_gpio_drivers_wiringpi_Native_digitalWrite
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    digitalRead
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_sunit_gpio_drivers_wiringpi_Native_digitalRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    analogWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sunit_gpio_drivers_wiringpi_Native_analogWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sunit_gpio_drivers_wiringpi_Native
 * Method:    analogRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sunit_gpio_drivers_wiringpi_Native_analogRead
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
